version: '3'
services:
  web:
    build: .
    image: render-example-laravel
    command: sh -c 'php artisan migrate --force && php-fpm'
    environment:
      APP_KEY: base64:dDtG/UP/BZK/e/kykgur3FqHl3p9B2LbdvsdO9YJIRY=
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://erp-team3.onrender.com
      DB_CONNECTION: mysql
      DB_HOST: sql107.epizy.com
      DB_PORT: 3306
      DB_DATABASE: epiz_33819856_erp
      DB_USERNAME: epiz_33819856
      DB_PASSWORD: ZTObgE2OjgfGQ3P
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    volumes:
      - ./:/app
    working_dir: /app
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: render
